<a href="https://colab.research.google.com/github/takemyt1me/ML_practice/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pandas practice**

In [ ]:
import pandas as pd

sr = pd.Series([100, 200, 300], index = ["one_hundred", "two_hundred", "three_hunderd"])

print(sr.values)


[100 200 300]


In [ ]:
values = [[1,2,3],[4,5,6],[7,8,9]]
index = ['one', 'two', 'three']
columns = ['A','B','C']

df = pd.DataFrame(values, index=index, columns=columns)

print(df)

       A  B  C
one    1  2  3
two    4  5  6
three  7  8  9


In [ ]:
data = {
    'student_id':['2022170969', '2022170973','2022170974','2022170991','2022171000'],
    'student_name':['유재형', '전성운','황건호','김경진','이재영'],
    'score':['90.72','78.09','98.43','64.19','81.30']
}

df = pd.DataFrame(data)
print(df)

print(df.head(2))
print(df.tail(3))
print(df['student_id'])

   student_id student_name  score
0  2022170969          유재형  90.72
1  2022170973          전성운  78.09
2  2022170974          황건호  98.43
3  2022170991          김경진  64.19
4  2022171000          이재영  81.30
   student_id student_name  score
0  2022170969          유재형  90.72
1  2022170973          전성운  78.09
   student_id student_name  score
2  2022170974          황건호  98.43
3  2022170991          김경진  64.19
4  2022171000          이재영  81.30
0    2022170969
1    2022170973
2    2022170974
3    2022170991
4    2022171000
Name: student_id, dtype: object


**Tensor practice**

In [5]:
import numpy as np

#t = np.array([0.,1.,2.,3.,4.,5.,6.])
#print(t)
#print('Rank of t:', t.ndim)
#print('Shape of t:', t.shape)

t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.,],[10.,11.,12.]])
print(t)
print('Rank of t:', t.ndim)
print('Shape of t:', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank of t: 2
Shape of t: (4, 3)


In [9]:
import torch

tn= torch.FloatTensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.,],[10.,11.,12.]])
print(tn)
print(tn.dim())
print(tn.shape)
print(tn.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
torch.Size([4, 3])


**Broadcasting**

Matrix 간의 연산 시 Matrix size를 자동으로 조정해서 계산함

In [10]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

print(m1.matmul(m2))

tensor([[ 5.],
        [11.]])
